version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env

  nodejs:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.webserver
    image: paketobuildpacks/nodejs:latest
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      # - node_modules:/home/node/app/node_modules

    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm rebuild esbuild
        npx prisma generate
        npm run build
        npm run start

  prisma:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "4100:4100"
    restart: unless-stopped
