version: '3'

services:
  database:
    image: postgres:latest
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:latest
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ["npm", "install", "&&", "npm", "build" , "&&", "npm", "start"]
